// Tooltip copy for every front-panel control and soft key, each deep-linking into the owner's manual.
export interface HelpEntry { title: string; text: string; anchor: string }

export const MANUAL_URL = '/manual/';

export const HELP: Record<string, HelpEntry> = {
  pads: { title: 'Drum pads', text: 'Hit to play the sound assigned in the current program. Velocity comes from where you strike (or key Z X C V, A S D F, Q W E R, 1 2 3 4). Hold with NOTE REPEAT for rolls.', anchor: 'pads' },
  bank: { title: 'PAD BANK', text: 'Four banks of 16 pads: A01 to D16. Each bank plays a different set of notes in the program.', anchor: 'pads' },
  fullLevel: { title: 'FULL LEVEL', text: 'Every pad hit plays at maximum velocity (127) while the LED is on. In the Name window it toggles upper and lower case.', anchor: 'full-level' },
  sixteenLevels: { title: '16 LEVELS', text: 'Spread one sound over the 16 pads in steps of velocity, tuning, decay, attack or filter. Press to set up, press again to turn off.', anchor: 'sixteen-levels' },
  nextSeq: { title: 'NEXT SEQ', text: 'Queue the sequence that plays after the current one ends. SUDDEN switches immediately; PAD picks a sequence from the pads.', anchor: 'next-sequence' },
  trackMute: { title: 'TRACK MUTE', text: 'Turn tracks on and off from the pads while the sequence plays. Hold SOLO and hit a pad to solo a track.', anchor: 'track-mute' },
  recGain: { title: 'REC GAIN', text: 'Input level for SAMPLE mode. Watch the meter and keep the peaks out of the top segment.', anchor: 'sampling' },
  volume: { title: 'MAIN VOLUME', text: 'Master output level of the machine.', anchor: 'basics' },
  f: { title: 'Function keys', text: 'F1 to F6 press the six soft keys printed on the bottom line of the LCD. Reversed labels jump to a page; framed labels run an action.', anchor: 'soft-keys' },
  mode: { title: 'MODE keypad', text: 'Hold SHIFT and press a number to change mode, as printed above each key: 1 SONG, 2 MISC, 3 LOAD, 4 SAMPLE, 5 TRIM, 6 PROGRAM, 7 MIXER, 8 OTHER, 9 MIDI/SYNC, 0 SAVE. Without SHIFT the keys type numbers into the field under the cursor; ENTER confirms.', anchor: 'modes' },
  main: { title: 'MAIN SCREEN', text: 'Back to the main sequencer screen from anywhere, closing any window.', anchor: 'main-screen' },
  window: { title: 'OPEN WINDOW', text: 'Open the settings window for the field under the cursor. Most fields have one. Press again to close it.', anchor: 'windows' },
  data: { title: 'DATA wheel', text: 'Turn to change the field under the cursor. Faster turns move in bigger steps. Scroll on it with the mouse wheel, or use [ and ] on the keyboard.', anchor: 'data-wheel' },
  cursor: { title: 'CURSOR', text: 'Move between the fields on the LCD. Only data fields can be landed on.', anchor: 'cursor' },
  after: { title: 'AFTER / ASSIGN', text: 'AFTER lets the NOTE VARIATION slider shape notes as the sequence plays back. SHIFT + AFTER opens the ASSIGN screen where you choose which note and parameter the slider controls.', anchor: 'note-variation' },
  nv: { title: 'NOTE VARIATION slider', text: 'Bends one parameter of the assigned note in real time: tuning, decay, attack or filter. The position is recorded with each hit.', anchor: 'note-variation' },
  tap: { title: 'TAP TEMPO / NOTE REPEAT', text: 'Tap on the beat to set the tempo. Hold it while playing and hold a pad to repeat the pad at the Timing value; pad pressure sets the velocity.', anchor: 'tap-tempo' },
  undo: { title: 'UNDO SEQ', text: 'Take back the last recording or edit of the sequence. Press again to redo. Only valid right after the take.', anchor: 'undo' },
  erase: { title: 'ERASE', text: 'While overdubbing, hold ERASE and a pad to erase that sound as the sequence plays over it. While stopped, it opens the Erase window for a range, a track or one event type.', anchor: 'erase' },
  step: { title: 'STEP < >', text: 'Move the position by one Timing value (or one tick when Timing is OFF). With GO TO held: jump to the previous or next event on the track.', anchor: 'locate' },
  goto: { title: 'GO TO', text: 'Tap to open the Locate window with nine stored positions. Hold with BAR << or >> to jump to the start or end.', anchor: 'locate' },
  bar: { title: 'BAR << >>', text: 'Move the position one bar back or forward. With GO TO held: start or end of the sequence.', anchor: 'locate' },
  rec: { title: 'REC', text: 'Arm recording: press REC then PLAY (or PLAY START). REC replaces what was on the track as the position passes over it. Pressing it during playback punches in and out.', anchor: 'recording' },
  overdub: { title: 'OVER DUB', text: 'Like REC, but adds to what is already on the track. A looping REC take switches to OVER DUB after the first pass by itself.', anchor: 'recording' },
  stop: { title: 'STOP', text: 'Stop playback and recording. The position stays where you stopped.', anchor: 'transport' },
  play: { title: 'PLAY', text: 'Play from the current position (Now:).', anchor: 'transport' },
  playStart: { title: 'PLAY START', text: 'Play from the first bar. In SONG mode it starts the song from step 1.', anchor: 'transport' },
  lcd: { title: 'The LCD', text: 'Everything happens here: fields, windows and the six soft keys on the bottom line. The cursor is the reversed block.', anchor: 'lcd' },
  manual: { title: "Owner's Manual", text: 'The full manual: every mode, every window, and a keyboard reference.', anchor: '' },
  tips: { title: 'TIPS', text: 'Switch these hover tips on or off. The choice is remembered in this browser.', anchor: 'panel' },
  quickStart: { title: 'Quick start', text: 'A short guided tour of the machine: play the demo, hit the pads, drop in your own sounds, chop them and record a beat. Escape closes it.', anchor: 'quick-start' },
  panel: { title: 'OG or EZ', text: 'Two front panels over the same machine. OG is the original workflow with the LCD and modes; EZ is the simple one with plain words and a step grid. Switch any time; nothing is converted.', anchor: 'ez' },
  account: { title: 'Account', text: 'Sign in and the machine keeps your work in your account, so it follows you to any browser. Signed in, this shows your handle and whether the last change has synced.', anchor: '' },
  kits: { title: 'Kit library', text: 'Pad banks other people made on Chop Deck: sixteen sounds with their tuning, envelopes and levels. Play them in the page and send one to the machine; it lands in the LOAD tray.', anchor: 'loading' },
  samples: { title: 'Samples library', text: 'Records, breaks and hits people have shared for chopping. Play one in the page and send it to the machine; it lands in the LOAD tray with the Load a Sound window open. Put it on a pad, then slice it from the ZONE page of TRIM.', anchor: 'zone' },
  beats: { title: 'Beats', text: 'Beats people have published from their machines, with the whole project behind each one. Play them, open one on the machine to hear exactly how it was made, or remix it.', anchor: 'sequencing' },
  publishBeat: { title: 'Publish this beat', text: "Render a sequence or song with the machine's own engine and publish it with the project behind it: a page with a player and a share card, open on the machine, remix. Needs an account.", anchor: 'recording' },
  publishKit: { title: 'Publish this kit', text: 'Put the program on the pads into the kit library under your handle, sounds and all. Needs an account; you choose the licence.', anchor: 'programs' },
};

/** Soft-key help by label. Labels are what the screens print; a few appear in several modes with the same meaning. */
const SOFT: Record<string, { text: string; anchor: string }> = {
  STEP: { text: 'Open STEP EDIT: the list of events at the current position.', anchor: 'step-edit' },
  EDIT: { text: 'Open the EDIT screen (copy, duration, velocity, transpose, bars, track move) or, in TRIM, the Edit window of sound operations.', anchor: 'edit-screen' },
  TRMUTE: { text: 'Mute or unmute the current track (ON:YES/NO).', anchor: 'tracks' },
  SOLO: { text: 'Solo the current track; press again to release. On the TRACK MUTE page, hold it and hit a pad.', anchor: 'track-mute' },
  'TR -': { text: 'Previous track.', anchor: 'tracks' },
  'TR +': { text: 'Next track.', anchor: 'tracks' },
  'DO IT': { text: 'Run the action shown in the window. Most edits can be taken back with UNDO SEQ.', anchor: 'soft-keys' },
  CANCEL: { text: 'Close the window without doing anything.', anchor: 'windows' },
  CLOSE: { text: 'Close the window.', anchor: 'windows' },
  DELETE: { text: 'Delete the selected item (a confirmation follows for anything that cannot be undone).', anchor: 'windows' },
  COPY: { text: 'Copy the selected item. In STEP EDIT it copies the selected events to the clipboard.', anchor: 'step-edit' },
  PASTE: { text: 'Paste the clipboard at the current position.', anchor: 'step-edit' },
  INSERT: { text: 'Insert a new item at the current position or after the selected step.', anchor: 'step-edit' },
  TC: { text: 'Hold and turn the DATA wheel to change the timing value.', anchor: 'timing' },
  PLAY: { text: 'Audition the selection at full velocity.', anchor: 'note-params' },
  'PLAY X': { text: 'Audition the sound region chosen in the PLAY X: field. Release to stop.', anchor: 'trim' },
  TRIM: { text: 'Start and end points of the sound.', anchor: 'trim' },
  LOOP: { text: 'Loop start and length.', anchor: 'loop-page' },
  ZONE: { text: 'Divide the sound into zones for slicing.', anchor: 'zone' },
  PARAMS: { text: 'Level, tune and beat loop of the sound, or the note parameters of a program.', anchor: 'params' },
  ASSIGN: { text: 'Which sound each pad plays.', anchor: 'assign' },
  DRUM: { text: 'Which program each DRUM slot holds.', anchor: 'drum' },
  PURGE: { text: 'Delete every sound not used by any program.', anchor: 'purge' },
  AUTO: { text: 'Spread one sound chromatically across all notes.', anchor: 'purge' },
  STEREO: { text: 'Level and pan per pad.', anchor: 'mixer' },
  INDIV: { text: 'Individual outputs (not available in a browser).', anchor: 'mixer' },
  FXSEND: { text: 'Effect bus and send level per pad.', anchor: 'mixer' },
  SETUP: { text: 'Master level and mixer sources.', anchor: 'mixer' },
  FXEDIT: { text: 'Edit the two multi-effects and two reverbs.', anchor: 'mixer' },
  'ALL CH': { text: 'Link every strip so one change moves them all. CLEAR unlinks.', anchor: 'mixer' },
  CLEAR: { text: 'Unlink the strips, or clear the queued next sequence.', anchor: 'mixer' },
  LOAD: { text: 'Load files from the browser disk or the import tray.', anchor: 'disk' },
  SAVE: { text: 'Save sequences, programs, sounds, mixdowns and project bundles.', anchor: 'disk' },
  FORMAT: { text: 'Wipe the browser disk.', anchor: 'disk' },
  PICK: { text: 'Choose files from your computer to import.', anchor: 'loading' },
  KEEP: { text: 'Keep the new sound in memory and on the chosen pad.', anchor: 'sampling' },
  DSCARD: { text: 'Drop the file without loading it.', anchor: 'loading' },
  RETRY: { text: 'Throw the take away and record again.', anchor: 'sampling' },
  RECORD: { text: 'Arm sampling; recording starts at the threshold or with START.', anchor: 'sampling' },
  START: { text: 'Start recording now.', anchor: 'sampling' },
  STOP: { text: 'End the take.', anchor: 'sampling' },
  RESET: { text: 'Reset the peak hold on the meters.', anchor: 'sampling' },
  PEAK: { text: 'Reset the peak hold on the meters.', anchor: 'sampling' },
  SUDDEN: { text: 'Switch to the next sequence right now.', anchor: 'next-sequence' },
  PAD: { text: 'Pick the next sequence from the pads.', anchor: 'next-sequence' },
  CONVRT: { text: 'Convert the song into one long sequence, or convert a sound between stereo, mono and sample rates.', anchor: 'song' },
  EVENTS: { text: 'Copy, duration, velocity and transpose edits on a time range.', anchor: 'edit-screen' },
  BARS: { text: 'Copy whole bars into another sequence.', anchor: 'edit-screen' },
  TRMOVE: { text: 'Move a track to another position.', anchor: 'edit-screen' },
  USER: { text: 'Defaults for new sequences.', anchor: 'user' },
  SELECT: { text: 'Pick the highlighted track to move.', anchor: 'edit-screen' },
  PUNCH: { text: 'Automatic punch in and out.', anchor: 'misc' },
  TRANS: { text: 'Playback transpose for MIDI tracks; FIX makes it permanent.', anchor: 'misc' },
  '2NDSEQ': { text: 'A second sequence that plays alongside.', anchor: 'misc' },
  TURNON: { text: 'Switch the function on.', anchor: 'misc' },
  OFF: { text: 'Switch the function off.', anchor: 'misc' },
  FIX: { text: 'Write the transpose into the note data permanently.', anchor: 'misc' },
  SYNC: { text: 'MIDI clock in and out.', anchor: 'midi' },
  PORTS: { text: 'Bind MIDI devices to the input and outputs A and B.', anchor: 'midi' },
  MIDISW: { text: 'Footswitch controller functions.', anchor: 'midi' },
  PANIC: { text: 'All notes off on every MIDI channel and voice.', anchor: 'midi' },
  OTHERS: { text: 'Tap averaging and the keyboard reference.', anchor: 'other' },
  INIT: { text: 'Factory reset (asks first).', anchor: 'other' },
  'VER.': { text: 'OS version.', anchor: 'other' },
  HELP: { text: 'Turn the keyboard reference page.', anchor: 'keyboard' },
  STORE: { text: 'Store the current position into the selected memory.', anchor: 'locate' },
  'GO TO': { text: 'Jump to the position or memory under the cursor.', anchor: 'locate' },
  NOW: { text: 'Set the selected tempo change to the current position.', anchor: 'tempo-change' },
  'IN/DEL': { text: 'Insert blank bars or delete a range of bars.', anchor: 'main-screen' },
  'ALL SQ': { text: 'Delete every sequence.', anchor: 'main-screen' },
  'ALL TR': { text: 'Delete every track.', anchor: 'tracks' },
  SOUND: { text: 'Choose the metronome sound.', anchor: 'count' },
  BPM: { text: 'Work the stretch ratio out from a source and a target tempo.', anchor: 'edit-sound' },
  'ZOOM-': { text: 'Zoom out of the waveform.', anchor: 'trim' },
  'ZOOM+': { text: 'Zoom into the waveform.', anchor: 'trim' },
  NEW: { text: 'Create a new program or folder.', anchor: 'assign' },
  RENAME: { text: 'Rename the selected file or folder.', anchor: 'disk' },
  RPLACE: { text: 'Paste, replacing events of the same kind at the position.', anchor: 'step-edit' },
  MERGE: { text: 'Paste on top of what is there.', anchor: 'step-edit' },
  'ON/OFF': { text: 'Switch the effect module under the cursor on or off.', anchor: 'mixer' },
  ENTER: { text: 'Keep the name.', anchor: 'name' },
  'DRUM 1': { text: 'Edit the program in DRUM slot 1.', anchor: 'drum' },
  'DRUM 2': { text: 'Edit the program in DRUM slot 2.', anchor: 'drum' },
  'DRUM 3': { text: 'Edit the program in DRUM slot 3.', anchor: 'drum' },
  'DRUM 4': { text: 'Edit the program in DRUM slot 4.', anchor: 'drum' },
};

/** Help for the soft key printed at slot `index` with `label`. */
export function softKeyHelp(label: string, index: number): HelpEntry | null {
  if (!label) return null;
  const hit = SOFT[label.toUpperCase()];
  return { title: `F${index + 1}: ${label}`, text: hit?.text ?? `A soft key of this screen; press it or F${index + 1}.`, anchor: hit?.anchor ?? 'soft-keys' };
}
